name: Format Python code with Black

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          version: '24.4.0' # Or other desired Black version
          # Alternatively, read version from pyproject.toml:
          # use_pyproject: true
